version: '3.0'
services:
  reflector:
    build: reflector
    restart: always
    environment:
      REFLECTOR_DOMAIN: demo.my-devices.net
      REFLECTOR_LICENSE: /home/reflector/etc/reflector.license
      HTTP_PORT: 8000
      MYSQL_DATABASE: reflector
      MYSQL_USERNAME: reflector
      MYSQL_PASSWORD: reflector
      MYSQL_HOST: mariadb
      REDIS_HOST: redis
      REDIS_PORT: 6379
      LOGCHANNEL: file
      LOGPATH: /home/reflector/var/log/reflector.log
    volumes:
      - logvolume:/home/reflector/var/log

volumes:
  logvolume:
